name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build & Push Images"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy Mongo
      - name: Deploy Mongo
        run: kubectl apply -f k8s/mongo-deployment.yaml

      # Deploy Backend
      - name: Deploy Backend
        run: kubectl apply -f k8s/backend-deployment.yaml

      # Deploy Frontend
      - name: Deploy Frontend
        run: kubectl apply -f k8s/frontend-deployment.yaml

