name: Build and Push Frontend Image

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_USERNAME }}/frontend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} ./frontend
          docker tag ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} ${{ env.DOCKER_REPOSITORY }}:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.DOCKER_REPOSITORY }}:latest
